included:
    - GameDex

excluded:
    - Pods
    - Carthage
    - GameDex/Resources/Assets.swift
    - GameDex/Resources/Strings.swift

disabled_rules:
    - trailing_whitespace
    - force_cast
    - void_return
    - control_statement
    - implicit_getter
    - unused_closure_parameter
    - blanket_disable_command
    - empty_enum_arguments
    - function_body_length
    - class_delegate_protocol
    - for_where
    - unused_optional_binding

line_length: 200

function_parameter_count: 4
cyclomatic_complexity: 15
type_body_length: 300
file_length: 500
identifier_name:
  min_length: 1

